---
- name: Configure /etc/auto.master.d/data.autofs
  ansible.builtin.lineinfile:
    path: /etc/auto.master.d/data.autofs
    line: /data /etc/auto.data nfsvers=3
    create: yes
    owner: root
    group: root
    mode: '0644'
  notify: Restart autofs

- name: Configure /etc/auto.data
  ansible.builtin.template:
    src: auto.data.j2
    dest: /etc/auto.data
    owner: root
    group: root
    mode: '0644'
  notify: Restart autofs
